image:
  registry: "amr-fm-registry.caas.intel.com/esh-user/"
  uiTag: "core_nginx_1"
  pullPolicy: IfNotPresent

global:
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
  app_backend_url: "/v1/chatqna"

uiService:
  type: ClusterIP
  port: 8102
  targetPort: 8102
