services:
  video-publisher:
    container_name: vrb_video_publisher
    image: vrb_video_publisher:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    read_only: true
    security_opt:
      - no-new-privileges
    privileged: false
    tty: true
    entrypoint: [ "./run.sh" ]
    ports:
      - "8090:8080"
    environment:
      - no_proxy=$no_proxy
      - http_proxy=$http_proxy
      - https_proxy=$https_proxy
      # - RABBITMQ_HOST=${RABBITMQ_SERVICE}
      # - RABBITMQ_PORT=1883
      # - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      # - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      # - MINIO_SERVER=${MINIO_SERVER}
      # - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      # - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME}
      - EMBEDDING_HOST=${EMBEDDING_HOST:-multimodal-embedding-serving}
      - EMBEDDING_PORT=${EMBEDDING_PORT:-8000}
      - VDMS_HOST=${VDMS_HOST:-vdms-vector-db}
      - VDMS_PORT=${VDMS_PORT:-55555}
      - ADD_TIMESTAMP_TO_METADATA=false
      - RUN_MODE=EVA
      # Default Detection and Classification Device
      - DETECTION_DEVICE=CPU
      - ADD_UTCTIME_TO_METADATA=true
      - HTTPS=false # Make it "true" to enable SSL/TLS secure mode, mount the generated certificates
      - MTLS_VERIFICATION=false # if HTTPS=true, enable/disable client certificate verification for mTLS
      - REST_SERVER_PORT=8080
    volumes:
      - vol_evam_pipeline_root:/var/cache/pipeline_root:uid=1999,gid=1999
      - "/run/udev:/run/udev:ro"
      - "/dev:/dev"
      - "/tmp:/tmp"
      - ../ov_models/:/home/pipeline-server/models
      - ../resources/videos:/home/pipeline-server/resources/videos
      - ../resources/models/:/home/pipeline-server/resources/models
      - ../resources/conf/:/home/pipeline-server/resources/conf
    group_add:
      # render group ID for ubuntu 20.04 host OS
      - "109"
      # render group ID for ubuntu 22.04 host OS
      - "110"
    device_cgroup_rules:
      # Default run - device-cgroup-rule='c 189:* rmw'
      # Selective rules can be applied for deployment
      - 'c 189:* rmw'
      - 'c 209:* rmw'
      - 'a 189:* rwm'
    devices:
      - "/dev:/dev"
    depends_on:
      - multimodal-embedding-serving
      - vdms-vector-db
    networks:
      - app_network
  multimodal-embedding-serving:
    image: intel/multimodal-embedding-serving:latest
    container_name: multimodal-embedding-serving
    ports:
      - '${EMBEDDING_SERVER_PORT:-9777}:8000'
    ipc: host
    environment:
      no_proxy: ${no_proxy},localhost,video-publisher,vdms-vector-db,multimodal-embedding-serving
      no_proxy_env: ${no_proxy},localhost,video-publisher,vdms-vector-db,multimodal-embedding-serving
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      EMBEDDING_MODEL_NAME: ${EMBEDDING_MODEL_NAME}
      EMBEDDING_DEVICE: ${EMBEDDING_DEVICE}
      EMBEDDING_USE_OV: ${EMBEDDING_USE_OV}
      EMBEDDING_OV_MODELS_DIR: ${EMBEDDING_OV_MODELS_DIR:-/app/ov_models}
      DEFAULT_START_OFFSET_SEC: ${DEFAULT_START_OFFSET_SEC:-0}
      DEFAULT_CLIP_DURATION: ${DEFAULT_CLIP_DURATION:--1}
      DEFAULT_NUM_FRAMES: ${DEFAULT_NUM_FRAMES:-64}
      OV_PERFORMANCE_MODE: ${OV_PERFORMANCE_MODE:-THROUGHPUT}
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - ${USER_GROUP_ID:-1000}
      - ${VIDEO_GROUP_ID:-44}
      - ${RENDER_GROUP_ID:-1002}
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD-SHELL', 'curl -f http://localhost:8000/health || exit 1' ]
      interval: 10s
      timeout: 10s
      retries: 40
      start_period: 5s
    networks:
      - app_network
    volumes:
      - ov-models:/home/appuser/.cache/huggingface
      # - data-prep:/tmp/dataprep
      - ov-models:${EMBEDDING_OV_MODELS_DIR:-/app/ov_models}

  vdms-vector-db:
    image: intellabs/vdms:v2.11.0
    ipc: host
    environment:
      - no_proxy=${no_proxy},localhost,video-publisher,vdms-vector-db
      - no_proxy_env=${no_proxy},localhost,video-publisher,vdms-vector-db
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - OVERRIDE_db_root_path=/db
      - OVERRIDE_images_path=/db/images
      - OVERRIDE_descriptors_path=/db/descriptors
      - OVERRIDE_blobs_path=/db/blobs
      - OVERRIDE_pmgd_path=/db/graph
    ports:
      - '${VDMS_VDB_HOST_PORT}:55555'
    volumes:
      - vdms-db:/db
    networks:
      - app_network

networks:
  app_network:
    driver: "bridge"

volumes:
  vol_evam_pipeline_root:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  ov-models:
    driver: local
  vdms-db:
    driver: local
