model_settings:
  EMBEDDING_MODEL_ID: "BAAI/bge-small-en-v1.5"
  RERANKER_MODEL_ID: "BAAI/bge-reranker-base"
  LLM_MODEL_ID: "Intel/neural-chat-7b-v3-3"
  # MAX_TOKENS: 30
  PROMPT_TEMPLATE: "
    ### System:
    Use the following pieces of context from retrieved
    dataset to answer the question. Do not make up an answer if there is no
    context provided to help answer it.

    ### Context:
    {context}

    ### User:
    {question}

    ### Assistant:
    "
  # PROMPT_TEMPLATE: "
  #   <|system|>
  #   Use the following pieces of context from retrieved
  #   dataset to answer the question. Do not make up an answer if there is no
  #   context provided to help answer it.<|end|>

  #   <|context|>
  #   Context:
  #   ---------
  #   {context}
  #   <|end|>

  #   <|user|>
  #   ---------
  #   Question: {question}
  #   ---------
  #   <|end|>

  #   <|assistant|>
  #   Answer:
  #   "